builds:
  - id: bor
    main: ./cmd/bor
    binary: bor
    ldflags: -s -w -X main.version={{.Version}}
    env: [CGO_ENABLED=0]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

  - id: reconcile
    main: ./arbiter/cmd/reconcile
    binary: reconcile
    ldflags: -s -w -X main.version={{.Version}}
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]

archives:
  - id: bor-archives
    builds: [bor]
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "bor-{{ .Os }}-{{ .Arch }}"

  - id: reconcile-archives
    builds: [reconcile]
    format: binary
    name_template: "reconcile-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc

brews:
  - name: bor
    ids: [bor-archives]
    repository:
      owner: jmaddaus
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/jmaddaus/boxofrocks
    description: "CLI issue tracker backed by GitHub Issues"
    install: |
      bin.install "bor"

scoops:
  - name: bor
    ids: [bor-archives]
    repository:
      owner: jmaddaus
      name: scoop-bucket
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/jmaddaus/boxofrocks
    description: "CLI issue tracker backed by GitHub Issues"
