name: 'Box of Rocks Reconciler'
description: 'Reconciles boxofrocks events on GitHub Issues'
inputs:
  issue-number:
    description: 'The issue number to reconcile'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download reconcile binary
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release download --repo jmaddaus/boxofrocks --pattern "reconcile-linux-amd64" --dir /tmp
        gh release download --repo jmaddaus/boxofrocks --pattern "checksums.txt" --dir /tmp
        cd /tmp && grep reconcile-linux-amd64 checksums.txt | sha256sum --check
        mv /tmp/reconcile-linux-amd64 /tmp/reconcile
        chmod +x /tmp/reconcile
    - name: Run reconciliation
      shell: bash
      run: /tmp/reconcile
      env:
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
